name: ss-web

services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile.dev
        ports:
            - "3000:3000"
        develop:
            watch:
                - path: ../src
                  action: sync
                  target: /app/src
        networks:
            - star-sync


networks:
    # assuming ss-deploy's db is running
    star-sync:
        driver: bridge
        name: star-sync_star-sync
        external: true

